language: java
jdk:
  - openjdk8

## Export GPG details
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  mvn --settings .settings.xml clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

## Build and release to maven central
script:
  mvn --settings .settings.xml clean deploy -DskipTests=true -Dmaven.javadoc.skip=false -B -U

## Get the project version
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

## Create release in Github
deploy:
  provider: releases
  api_key:
    secure: im6enPaCVQ91auK17R1+hDiA2rhjDQEDZvv2wfJznqanJm4veuINK1Ak3TMlVJVzz2TixmEYtGTtGAOL/IwbylhjZKfpJJPeptZ9ztsKHXpdAdnAaPpnVgGAaW4FXksmxzlqRyB4xfY48MFpsHEzuhTYONvPTvvlJt4uUResR65g1h8/ypXsJMSHpzegvoVsYRevYfrJq1OUgI6UIKXtb9txIbGpwrN64r/gpWz8k6se2L9WXFP8q3wHp+RcDCa2RnWxsk/Q8fxcJrrxLt9JAnu+VYbiLRtNjNPrE/fcw7rCkC25deVWY+P+nzxI6P5pIZYE7mue0G5B6i5yZux+ZyWxMcdiB6J1G1MFiBYXVJUN9oqX4G9Q4soWDovzq+Z3R727fA1wBeMd1B1/DSBPen9GM4gXsZXGI910SUDDRfUbfhytDesu+k2F4WoJGjIjoAEE4B24uCYNMPqqFpUxXIGLLFQ6iB5tS0pVoqFmaWOBJkwTVK3w8tpMYlNxFUsc8iN+ayT5tVxGrYWtZhA740Kegu2sv5KZAYReG8IiP8V+SXB4meW2de11PvOji0VqnI6U8IGQ28JkAJPpV/DZUtrFn7qnDijioGnVGDnrW4UYbXMQvjOc+3WIMB4ooUgKI16rIxyiVpoGdhTeN8W+UjMwUJO0CGqz4g8/OP+iQ54=
  file:
    - "target/ordered-classloader-$project_version.jar"
    - "target/ordered-classloader-$project_version-javadoc.jar"
    - "target/ordered-classloader-$project_version-sources.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: sgyyz/ordered-classloader
  name: $project_version

cache:
  directories:
    - ~/.m2/repository
